# Generated by Django 4.2.2 on 2023-08-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subtask',
            field=models.TextField(blank=True),
        ),
    ]
