# Generated by Django 4.2.2 on 2023-08-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='subtask',
            new_name='subtasks',
        ),
    ]
