# Generated by Django 4.2.2 on 2023-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_rename_subtask_ticket_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subtasks',
            field=models.JSONField(blank=True),
        ),
    ]
